name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  go-mod-tidy:
    name: go mod tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.21.0"
      - run: go mod tidy
      - run: git diff --exit-code go.mod go.sum
  test:
    name: test
    needs: go-mod-tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.21.0"
      - name: run golang tests
        run: go test ./...
  build:
    name: Docker build and push
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: ${{ github.event_name == 'release' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/s3-tester:latest,${{ secrets.DOCKERHUB_USERNAME }}/s3-tester:${{github.ref_name}}